Repository AdobeDocs/commerce-webapi, pull requests merged in 2022-07, with the labels that each got.

#18 COMDOX-230: Migrate intro for inventory module
  src/data/navigation/sections/rest.js
  src/pages/_images/inventory-diagram-stock.png
  src/pages/rest/modules/inventory/index.md
  src/pages/rest/modules/inventory/link-stocks-sources.md
  src/pages/rest/modules/inventory/manage-sources.md
Labels: migration

#19 COMDOX-273: Migrate B2B Developer Guide
  src/data/navigation/sections/rest.js
  src/pages/_images/payment-on-credit.png
  src/pages/_images/quote-checkout-process.png
  src/pages/_images/quote-statuses.png
  src/pages/_images/quote-workflow.jpg
  src/pages/rest/b2b/company-credit.md
  src/pages/rest/b2b/company-object.md
  src/pages/rest/b2b/company-structures.md
  src/pages/rest/b2b/company-users.md
  src/pages/rest/b2b/company.md
  src/pages/rest/b2b/credit-manage.md
  src/pages/rest/b2b/extensions.md
  src/pages/rest/b2b/index.md
  src/pages/rest/b2b/integrations.md
  src/pages/rest/b2b/negotiable-checkout.md
  src/pages/rest/b2b/negotiable-manage.md
  src/pages/rest/b2b/negotiable-order-workflow.md
  src/pages/rest/b2b/negotiable-quote.md
  src/pages/rest/b2b/negotiable-update.md
  src/pages/rest/b2b/roles.md
  src/pages/rest/b2b/shared-cat-company.md
  src/pages/rest/b2b/shared-cat-manage.md
  src/pages/rest/b2b/shared-cat-product-assign.md
  src/pages/rest/b2b/shared-catalog.md
Labels: migration

#20 ACP2E-994: [Documentation] Add notice that Admin, Bearer and other types of tokens are not supported to skip providing of HTTP X-Captcha header.
  src/pages/rest/use-rest/protected-endpoints.md
Labels: Technical

#24 Update search-endpoint.md
  src/pages/rest/use-rest/search-endpoint.md
Labels: technical

#25 Truncating response for Algolia indexer
  src/pages/rest/tutorials/orders/order-create-order.md
Labels: bug

#21 COMDOX-230: Move inventory up a level
  src/data/navigation/sections/rest.js
  src/pages/rest/inventory/bulk-inventory.md
  src/pages/rest/inventory/check-salable-quantity.md
  src/pages/rest/inventory/in-store-pickup.md
  src/pages/rest/inventory/index.md
  src/pages/rest/inventory/link-stocks-sources.md
  src/pages/rest/inventory/manage-low-quantity.md
  src/pages/rest/inventory/manage-source-items.md
  src/pages/rest/inventory/manage-source-selection.md
  src/pages/rest/inventory/manage-sources.md
  src/pages/rest/inventory/manage-stocks.md
  src/pages/rest/modules/index.md
  src/pages/rest/tutorials/inventory/in-store-pickup.md
  src/pages/rest/tutorials/inventory/run-ssa.md
Labels: migration
