Repository AdobeDocs/commerce-webapi, pull requests merged in 2022-10, with the labels that each got.

#43 COMDOX-346: Restore workflow customizations
  .env.example
  .github/CODE_OF_CONDUCT.md
  .github/dependabot.yml
  .github/workflows/github-pages.yml
  .github/workflows/test-pull-request.yml
  CODE_OF_CONDUCT.md
  package.json
  yarn.lock
Labels: enhancement

#46 Bumped aio-theme
  package.json
  yarn.lock
Labels: dependencies

#48 Redocly setup
  package.json
  src/openapi/.redocly.yaml
  src/openapi/admin-schema-2.3.7.yaml
  src/openapi/admin-schema-2.4.5.yaml
  src/openapi/customer-schema-2.3.7.yaml
  src/openapi/customer-schema-2.4.5.yaml
  src/openapi/guest-schema-2.3.7.yaml
  src/openapi/guest-schema-2.4.5.yaml
  yarn.lock
Labels: migration

#49 Test and fix link checking
  .github/workflows/test-pull-request.yml
  src/pages/index.md
Labels: bug, dependencies

#50 COMDOX-258 Migrate ReDocly
  src/data/navigation/sections/rest.js
  src/pages/rest/quick-reference/index.md
Labels: migration
