Repository AdobeDocs/commerce-webapi, pull requests merged in 2023-04, with the labels that each got.

#116 COMDOX-596: Update gatsby-theme-aio to 4.9.0
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: dependencies, maintenance

#117 Remove glossary links
  src/pages/get-started/authentication/gs-authentication-oauth.md
  src/pages/get-started/authentication/gs-authentication-session.md
  src/pages/get-started/authentication/gs-authentication-token.md
  src/pages/get-started/authentication/index.md
  src/pages/get-started/create-integration.md
  src/pages/get-started/gs-curl.md
  src/pages/get-started/gs-web-api-request.md
  src/pages/get-started/gs-web-api-response.md
  src/pages/get-started/index.md
  src/pages/get-started/rest_front.md
  src/pages/get-started/soap-web-api-calls.md
  src/pages/get-started/web-api-functional-testing.md
  src/pages/graphql/tutorials/checkout/index.md
  src/pages/rest/modules/catalog/index.md
  src/pages/rest/quick-reference/generate-local.md
  src/pages/rest/tutorials/index.md
  src/pages/rest/tutorials/inventory/configure-environment.md
  src/pages/rest/tutorials/inventory/create-customer.md
  src/pages/rest/tutorials/inventory/create-invoice.md
  src/pages/rest/tutorials/inventory/create-order.md
  src/pages/rest/tutorials/inventory/prepare-for-checkout.md
  src/pages/rest/tutorials/orders/index.md
  src/pages/rest/tutorials/orders/order-add-items.md
  src/pages/rest/tutorials/orders/order-admin-token.md
  src/pages/rest/tutorials/orders/order-config-store.md
  src/pages/rest/tutorials/orders/order-create-customer.md
  src/pages/rest/tutorials/orders/order-create-invoice.md
  src/pages/rest/tutorials/orders/order-create-order.md
  src/pages/rest/tutorials/orders/order-create-quote.md
  src/pages/rest/tutorials/orders/order-create-shipment.md
  src/pages/rest/tutorials/orders/order-issue-refund.md
  src/pages/rest/tutorials/orders/order-prepare-checkout.md
  src/pages/rest/tutorials/prerequisite-tasks/index.md
  src/pages/rest/use-rest/anonymous-api-security.md
  src/pages/rest/use-rest/performing-searches.md
  src/pages/rest/use-rest/retrieve-filtered-responses.md
Labels: editorial, internal

#122 Fix linting errors
  src/pages/graphql/schema/products/interfaces/routable.md
Labels: editorial, internal, 2.4.7

#120 Add caching capability to "availableStores", "storeConfig", "country", "countries", "currency" and "customAttributeMetadata" GraphQl queries
  src/pages/graphql/usage/caching.md
Labels: technical, internal, 2.4.7

#123 Change routes to route
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/products/queries/route.md
Labels: bug, internal

#129 Move attributes queries out of Store
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/attributes/index.md
  src/pages/graphql/schema/attributes/queries/attributes-metadata.md
  src/pages/graphql/schema/attributes/queries/custom-attribute-metadata.md
  src/pages/graphql/schema/attributes/queries/index.md
  src/pages/graphql/schema/products/queries/products.md
  src/pages/graphql/usage/custom-filters.md
Labels: internal, maintenance

#127 LYNX-152: Documentation for attributesMetadata query
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/attributes/index.md
  src/pages/graphql/schema/attributes/queries/custom-attribute-metadata-v2.md
  src/pages/graphql/schema/attributes/queries/index.md
  src/pages/graphql/schema/store/queries/attributes-metadata.md
  src/pages/graphql/schema/store/queries/custom-attribute-metadata.md
Labels: new topic, internal, 2.4.7

#130 Port GQL directory changes to 2.4.7
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/attributes/queries/attributes-metadata.md
  src/pages/graphql/schema/attributes/queries/custom-attribute-metadata-v2.md
  src/pages/graphql/schema/attributes/queries/custom-attribute-metadata.md
  src/pages/graphql/schema/products/queries/products.md
  src/pages/graphql/usage/custom-filters.md
Labels: internal, maintenance

#131 Fix merge error
  src/data/navigation/sections/graphql.js
Labels: internal, maintenance
