Repository AdobeDocs/commerce-webapi, pull requests merged in 2023-01, with the labels that each got.

#67 COMDOX-429: Convert relative links to absolute (setShippingAddressesOnCart mutation)
  src/pages/_includes/graphql/cart-object-24.md
Labels: maintenance

#68 COMDOX-429: Revert formatting for arrays (setShippingAddressesOnCart mutation)
  src/pages/_includes/graphql/cart-object-24.md
Labels: editorial

#71 Add H1 to new ImportCsv API topic
  src/pages/rest/modules/import/index.md
Labels: editorial, 2.4.6

#72 Port Devdocs PR-3082 to Devsite
  src/pages/_includes/graphql/customer-orders-output.md
  src/pages/graphql/schema/customer/queries/customer.md
Labels: technical, 2.4.6, internal

#73 Port Devdocs PR-3055 to Devsite
  src/pages/_includes/graphql/cart-address-input-24.md
Labels: technical, 2.4.6, internal

#54 ACPT-858: Add gzip info to Documentation for Import API
  src/pages/rest/modules/import/index.md
Labels: technical

#62 ACPT-946: Add optional parameters to Documentation for Import API
  src/pages/rest/modules/import/index.md
Labels: major update, 2.4.6, internal

#74 Change 'routes' to 'route'
  src/pages/graphql/schema/products/queries/route.md
Labels: editorial

#70 Purchase Order and Purchase Order Rule GraphQL
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/b2b/purchase-order-rule/index.md
  src/pages/graphql/schema/b2b/purchase-order-rule/interfaces/condition.md
  src/pages/graphql/schema/b2b/purchase-order-rule/interfaces/index.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/create.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/delete.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/index.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/update.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/validate.md
  src/pages/graphql/schema/b2b/purchase-order-rule/queries/approval-flow.md
  src/pages/graphql/schema/b2b/purchase-order-rule/queries/index.md
  src/pages/graphql/schema/b2b/purchase-order-rule/queries/list.md
  src/pages/graphql/schema/b2b/purchase-order-rule/queries/metadata.md
  src/pages/graphql/schema/b2b/purchase-order-rule/queries/single.md
  src/pages/graphql/schema/b2b/purchase-order/index.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/add-comment.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/add-items-to-cart.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/approve.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/cancel.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/index.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/place-order.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/place.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/reject.md
  src/pages/graphql/schema/b2b/purchase-order/queries/enabled.md
  src/pages/graphql/schema/b2b/purchase-order/queries/index.md
  src/pages/graphql/schema/b2b/purchase-order/queries/list.md
  src/pages/graphql/schema/b2b/purchase-order/queries/single.md
Labels: new topic, 2.4.6, internal

#56 Add GraphQL reference
  README.md
  package.json
  spectaql/adobe-theme/stylesheets/custom.scss
  spectaql/config.yml
  spectaql/schema.json
  src/pages/graphql/reference.md
  static/graphql-api/index.html
  static/graphql-api/javascripts/spectaql.min.js
  static/graphql-api/stylesheets/spectaql.min.css
  yarn.lock
Labels: enhancement

#75 ACP2E-1598: [Documentation] Update GraphQL documentation to reflect changes introduced in ACP2E-1494
  src/pages/graphql/schema/products/interfaces/routable.md
Labels: technical, 2.4.7
