Repository AdobeDocs/commerce-webapi, pull requests merged in 2023-07, with the labels that each got.

#172 Remove duplicate section from left nav
  src/data/navigation/sections/graphql.js
Labels: internal, maintenance

#173 Nav fix for 247
  src/data/navigation/sections/graphql.js
Labels: internal, maintenance

#167 Add Catalog Service related product link info
  src/pages/_includes/graphql/catalog-service/product-view.md
  src/pages/graphql/schema/catalog-service/queries/products.md
Labels: technical, internal

#174 Update doc according to the changes introduced in ACP2E-2044
  src/pages/graphql/schema/cart/queries/cart.md
Labels: editorial, internal

#176 Add Recommendations GQL query
  src/pages/graphql/schema/product-recommendations/index.md
  src/pages/graphql/schema/product-recommendations/queries/index.md
  src/pages/graphql/schema/product-recommendations/queries/recommendations.md
Labels: new topic, internal

#177 Add recommendations query to TOC
  src/data/navigation/sections/graphql.js
Labels: editorial, internal

#179 Use include file in customer query
  src/pages/_includes/graphql/customer-address-output-24.md
  src/pages/graphql/schema/customer/mutations/create-address.md
  src/pages/graphql/schema/customer/mutations/update-address.md
  src/pages/graphql/schema/customer/queries/customer.md
Labels: editorial, internal

#181 GraphQL: Remove reference info from Store entities
  src/pages/graphql/schema/store/index.md
  src/pages/graphql/schema/store/mutations/index.md
  src/pages/graphql/schema/store/queries/available-stores.md
  src/pages/graphql/schema/store/queries/cms-blocks.md
  src/pages/graphql/schema/store/queries/cms-page.md
  src/pages/graphql/schema/store/queries/countries.md
  src/pages/graphql/schema/store/queries/country.md
  src/pages/graphql/schema/store/queries/currency.md
  src/pages/graphql/schema/store/queries/dynamic-blocks.md
  src/pages/graphql/schema/store/queries/index.md
  src/pages/graphql/schema/store/queries/store-config.md
Labels: internal, maintenance

#182 GraphQL: Remove reference info from Wishlist entities
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/wishlist/index.md
  src/pages/graphql/schema/wishlist/interfaces/index.md
  src/pages/graphql/schema/wishlist/interfaces/wishlist.md
  src/pages/graphql/schema/wishlist/mutations/add-items-to-cart.md
  src/pages/graphql/schema/wishlist/mutations/add-products.md
  src/pages/graphql/schema/wishlist/mutations/copy-products.md
  src/pages/graphql/schema/wishlist/mutations/create.md
  src/pages/graphql/schema/wishlist/mutations/delete.md
  src/pages/graphql/schema/wishlist/mutations/index.md
  src/pages/graphql/schema/wishlist/mutations/move-products.md
  src/pages/graphql/schema/wishlist/mutations/remove-products.md
  src/pages/graphql/schema/wishlist/mutations/update-products.md
  src/pages/graphql/schema/wishlist/mutations/update.md
  src/pages/graphql/schema/wishlist/queries/index.md
  src/pages/graphql/schema/wishlist/queries/wishlist.md
Labels: internal, maintenance

#151 Beta2: Different tasks from Custom product EAV in GraphQL epic (LYNX-52)
  src/pages/_includes/graphql/attribute-value-interface.md
  src/pages/_includes/graphql/cart-address-input-24.md
  src/pages/_includes/graphql/customer-address-output-24.md
  src/pages/_includes/graphql/customer-output-24.md
  src/pages/_includes/graphql/return.md
  src/pages/graphql/schema/attributes/queries/attributes-form.md
  src/pages/graphql/schema/attributes/queries/attributes-list.md
  src/pages/graphql/schema/attributes/queries/custom-attribute-metadata-v2.md
  src/pages/graphql/schema/cart/mutations/set-billing-address.md
  src/pages/graphql/schema/cart/mutations/set-shipping-address.md
  src/pages/graphql/schema/customer/queries/customer.md
  src/pages/graphql/schema/products/interfaces/attributes.md
  src/pages/graphql/schema/products/interfaces/pwa-implementations.md
  src/pages/graphql/schema/products/queries/products.md
Labels: major update, internal, 2.4.7

#183 GraphQL: Remove reference info from Gift Registry section
  src/pages/graphql/schema/gift-registry/index.md
  src/pages/graphql/schema/gift-registry/mutations/add-registrants.md
  src/pages/graphql/schema/gift-registry/mutations/create.md
  src/pages/graphql/schema/gift-registry/mutations/index.md
  src/pages/graphql/schema/gift-registry/mutations/move-cart-items.md
  src/pages/graphql/schema/gift-registry/mutations/remove-items.md
  src/pages/graphql/schema/gift-registry/mutations/remove-registrants.md
  src/pages/graphql/schema/gift-registry/mutations/remove.md
  src/pages/graphql/schema/gift-registry/mutations/share.md
  src/pages/graphql/schema/gift-registry/mutations/update-items.md
  src/pages/graphql/schema/gift-registry/mutations/update-registrants.md
  src/pages/graphql/schema/gift-registry/mutations/update.md
  src/pages/graphql/schema/gift-registry/queries/email-search.md
  src/pages/graphql/schema/gift-registry/queries/gift-registry.md
  src/pages/graphql/schema/gift-registry/queries/id-search.md
  src/pages/graphql/schema/gift-registry/queries/index.md
  src/pages/graphql/schema/gift-registry/queries/type-search.md
  src/pages/graphql/schema/gift-registry/queries/types.md
Labels: internal, maintenance

#185 GraphQL: Remove reference info from Orders section
  src/pages/graphql/schema/orders/index.md
  src/pages/graphql/schema/orders/interfaces/credit-memo-item.md
  src/pages/graphql/schema/orders/interfaces/index.md
  src/pages/graphql/schema/orders/interfaces/invoice-item.md
  src/pages/graphql/schema/orders/interfaces/order-item.md
  src/pages/graphql/schema/orders/interfaces/shipment-item.md
  src/pages/graphql/schema/orders/mutations/add-return-comment.md
  src/pages/graphql/schema/orders/mutations/add-return-tracking.md
  src/pages/graphql/schema/orders/mutations/index.md
  src/pages/graphql/schema/orders/mutations/remove-return-tracking.md
  src/pages/graphql/schema/orders/mutations/reorder-items.md
  src/pages/graphql/schema/orders/mutations/request-return.md
Labels: internal, maintenance
