Repository AdobeDocs/commerce-webapi, pull requests merged in 2023-02, with the labels that each got.

#77 Add purchase order GraphQL content
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/b2b/purchase-order-rule/index.md
  src/pages/graphql/schema/b2b/purchase-order-rule/interfaces/index.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/create.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/delete.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/index.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/update.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/validate.md
  src/pages/graphql/schema/b2b/purchase-order/index.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/add-comment.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/add-items-to-cart.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/approve.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/cancel.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/index.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/place-order.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/place-purchase-order.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/reject.md
  src/pages/graphql/schema/customer/queries/customer.md
Labels: new topic, 2.4.6, internal

#83 Fix rendering for the GraphQL API reference
  package.json
  src/pages/graphql/reference.md
  static/graphql-api/index.html
  yarn.lock
Labels: bug, dependencies

#82 COMDOX-390: Add overview sentence to the GQL schema
  spectaql/config.yml
  static/graphql-api/index.html
Labels: maintenance

#81 Tutorial on how to manage product images
  src/data/navigation/sections/rest.js
  src/pages/_images/api-frontend-new-image.png
  src/pages/_images/api-new-image.png
  src/pages/_images/delete-image-frontend.png
  src/pages/_images/list-product-images.png
  src/pages/_images/update-image-frontend.png
  src/pages/_images/update-new-image.png
  src/pages/rest/tutorials/image/delete.md
  src/pages/rest/tutorials/image/index.md
  src/pages/rest/tutorials/image/list.md
  src/pages/rest/tutorials/image/new.md
  src/pages/rest/tutorials/image/update.md
Labels: new topic

#88 Fix wrong description on is_subscribed
  src/pages/_includes/graphql/create-customer.md
Labels: bug, editorial

#89 Add link to GraphQL reference
  src/data/navigation/sections/graphql.js
Labels: editorial

#90 fix: table display in docs
  src/pages/graphql/schema/orders/mutations/request-return.md
Labels: editorial

#91 SpectaQL: Add text to null descriptions
  spectaql/schema.json
  static/graphql-api/index.html
Labels: bug, editorial

#94 Remove duplicate `product_sale_price` from query
  src/pages/graphql/schema/customer/queries/customer.md
Labels: technical

#85 Feature/fix graphql product interface page link
  src/pages/graphql/schema/products/queries/products.md
Labels: editorial, internal

#96 Add indexing workflow
  .github/workflows/index.yml
Labels: enhancement
