Repository AdobeDocs/commerce-webapi, pull requests merged in 2023-05, with the labels that each got.

#95 AC-7959: Create documentation for rate limiting feature
  src/pages/_images/api-security-rate-limiting.png
  src/pages/get-started/api-security.md
Labels: new topic, internal, 2.4.7

#136 LYNX-155: Update documentation of queries/mutations to include introduces custom_attributes fields
  src/pages/_includes/graphql/customer-address-input-24.md
  src/pages/_includes/graphql/customer-address-output-24.md
  src/pages/_includes/graphql/customer-output-24.md
  src/pages/graphql/schema/customer/mutations/create-address.md
  src/pages/graphql/schema/customer/mutations/create-v2.md
  src/pages/graphql/schema/customer/mutations/update-address.md
  src/pages/graphql/schema/customer/mutations/update-v2.md
  src/pages/graphql/schema/customer/queries/customer.md
Labels: major update, internal, 2.4.7

#138 [DATA-4821] Added in/low stock and updated query
  src/pages/_includes/graphql/catalog-service/product-view.md
  src/pages/graphql/schema/catalog-service/queries/products.md
Labels: technical

#133 LYNX-154: Documentation for attributeForms query
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/attributes/queries/attributes-form.md
Labels: new topic, internal, 2.4.7

#143 Update CustomerAddress.custom_attributes deprecation message and usage
  src/pages/_includes/graphql/customer-address-input-24.md
  src/pages/_includes/graphql/customer-address-output-24.md
  src/pages/graphql/schema/customer/mutations/create-address.md
  src/pages/graphql/schema/customer/mutations/update-address.md
Labels: major update, internal, 2.4.7

#146 Convert add-to-project-board to reusable workflow
  .github/workflows/add-to-project-board.yml
Labels: enhancement, maintenance

#147 LYNX-162: Add uids filters to entity queries custom_attriubtes fields
  src/pages/_includes/graphql/customer-address-output-24.md
  src/pages/_includes/graphql/customer-output-24.md
  src/pages/graphql/schema/customer/queries/customer.md
Labels: major update, internal, 2.4.7

#134 Update index.md
  src/pages/rest/modules/import/index.md
Labels: bug, technical, internal

#148 COMDOX-660: Added notes for 2.4.7-beta1 updates
  src/pages/_includes/graphql/customer-address-input-24.md
  src/pages/_includes/graphql/customer-address-output-24.md
  src/pages/_includes/graphql/customer-output-24.md
  src/pages/_includes/graphql/notes/beta-example.md
  src/pages/_includes/graphql/notes/beta.md
  src/pages/get-started/api-security.md
  src/pages/graphql/schema/attributes/queries/attributes-form.md
  src/pages/graphql/schema/attributes/queries/attributes-list.md
  src/pages/graphql/schema/attributes/queries/custom-attribute-metadata-v2.md
  src/pages/graphql/schema/customer/mutations/create-address.md
  src/pages/graphql/schema/customer/mutations/create-v2.md
  src/pages/graphql/schema/customer/mutations/update-address.md
  src/pages/graphql/schema/customer/mutations/update-v2.md
  src/pages/graphql/schema/customer/queries/customer.md
  src/pages/graphql/schema/products/interfaces/routable.md
  src/pages/graphql/usage/caching.md
Labels: editorial, internal, 2.4.7

#152 Revert "Merge pull request #147 from loginesta/LYNX-162"
  src/pages/_includes/graphql/customer-address-output-24.md
  src/pages/_includes/graphql/customer-output-24.md
  src/pages/graphql/schema/customer/queries/customer.md
Labels: maintenance, 2.4.7

#149 Separate 2.4.7-beta1 usage examples from 2.4.6 with tabbed code blocks
  src/pages/_includes/graphql/cache/queries-246.md
  src/pages/_includes/graphql/cache/queries-247beta.md
  src/pages/_includes/graphql/examples/create-address-246.md
  src/pages/_includes/graphql/examples/create-address-247beta.md
  src/pages/_includes/graphql/examples/create-v2-246.md
  src/pages/_includes/graphql/examples/create-v2-247beta.md
  src/pages/_includes/graphql/examples/update-address-246.md
  src/pages/_includes/graphql/examples/update-address-247beta.md
  src/pages/_includes/graphql/examples/update-v2-246.md
  src/pages/_includes/graphql/examples/update-v2-247beta.md
  src/pages/_includes/graphql/notes/beta-example.md
  src/pages/graphql/schema/customer/mutations/create-address.md
  src/pages/graphql/schema/customer/mutations/create-v2.md
  src/pages/graphql/schema/customer/mutations/update-address.md
  src/pages/graphql/schema/customer/mutations/update-v2.md
  src/pages/graphql/schema/customer/queries/customer.md
  src/pages/graphql/usage/caching.md
Labels: editorial, internal, 2.4.7
