Repository AdobeDocs/commerce-webapi, pull requests merged in 2023-06, with the labels that each got.

#142 SEG-699: Provide public documentation for new GraphQL endpoints
  src/pages/graphql/schema/store/queries/dynamic-blocks.md
Labels: technical, internal

#156 Minor maintenance update
  .github/workflows/github-pages.yml
  .nvmrc
  123.png
  package.json
  yarn.lock
Labels: maintenance

#150 B2B-2557 :Add documentation for the new B2B API
  src/data/navigation/sections/rest.js
  src/pages/_images/quote-workflow.jpg
  src/pages/_images/quote-workflow.svg
  src/pages/rest/b2b/integrations.md
  src/pages/rest/b2b/negotiable-by-seller-workflow.md
  src/pages/rest/b2b/negotiable-manage.md
  src/pages/rest/b2b/negotiable-quote.md
Labels: new topic, internal, 2.4.7

#160 Adding REST schemas for 2.4.7-beta
  src/openapi/admin-schema-2.4.7-beta.yaml
  src/openapi/customer-schema-2.4.7-beta.yaml
  src/openapi/guest-schema-2.4.7-beta.yaml
Labels: major update, internal, 2.4.7

#161 Add GraphQL API reference for Beta
  package.json
  spectaql/config_beta.yml
  spectaql/schema_beta.json
  src/data/navigation/sections/graphql.js
  src/pages/graphql/reference.md
  src/pages/graphql/reference/beta.md
  src/pages/graphql/reference/index.md
  static/graphql-api/beta/javascripts/spectaql.min.js
  static/graphql-api/beta/stylesheets/spectaql.min.css
Labels: major update, internal, 2.4.7

#139 Updates to rate limiting topic
  src/data/navigation/sections/get_started.js
  src/pages/get-started/api-security.md
  src/pages/get-started/rate-limiting.md
Labels: new topic, internal, 2.4.7

#162 Add `recommendations` query for PREX
  src/data/navigation/sections/graphql.js
  src/pages/_includes/graphql/product-recommendations/index.md
  src/pages/_includes/graphql/product-recommendations/queries/index.md
  src/pages/_includes/graphql/product-recommendations/queries/recommendations.md
  src/pages/graphql/schema/catalog-service/queries/products.md
Labels: new topic, internal

#154 Beta2: LYNX-162: Add uids filters to entity queries custom_attriubtes fields (redux)
  src/pages/_includes/graphql/customer-address-output-24.md
  src/pages/_includes/graphql/customer-output-24.md
  src/pages/graphql/schema/customer/queries/customer.md
Labels: major update, internal, 2.4.7

#168 Backing out Prex
  src/data/navigation/sections/graphql.js
  src/pages/_includes/graphql/product-recommendations/index.md
  src/pages/_includes/graphql/product-recommendations/queries/index.md
  src/pages/_includes/graphql/product-recommendations/queries/recommendations.md
Labels: internal, maintenance
