Repository AdobeDocs/commerce-webapi, pull requests merged in 2023-10, with the labels that each got.

#212 Fix typo error
  src/_includes/graphql/customer-orders-output.md
Labels: editorial

#216 Rename the test:links task
  package.json
Labels: enhancement, maintenance

#217 Update Catalog Service GQL ref
  src/_includes/graphql/catalog-service/product-view.md
Labels: editorial, internal

#218 COMDOX-801 Remove 2.3.7 schemas from REST API reference
  src/openapi/.redocly.yaml
  src/openapi/admin-schema-2.3.7.yaml
  src/openapi/customer-schema-2.3.7.yaml
  src/openapi/guest-schema-2.3.7.yaml
Labels: editorial, internal, maintenance

#219 Add source files for payment graphics
  src/pages/_images/graphql/src/authorize-net.drawio
  src/pages/_images/graphql/src/braintree-vault.drawio
  src/pages/_images/graphql/src/braintree.drawio
  src/pages/_images/graphql/src/payflow-flow-vault.drawio
  src/pages/_images/graphql/src/paypal-express-checkout.drawio
  src/pages/_images/graphql/src/paypal-hosted-pro.drawio
  src/pages/_images/graphql/src/paypal-payflow-link.drawio
  src/pages/_images/graphql/src/paypal-payflow-pro-vault.drawio
  src/pages/_images/graphql/src/paypal-payflow-pro.drawio
Labels: internal, maintenance
