Repository AdobeDocs/commerce-webapi, pull requests merged in 2023-03, with the labels that each got.

#98 Fix indexing
  .github/workflows/index.yml
  package.json
  src/pages/graphql/reference.md
  yarn.lock
Labels: bug

#100 Prepare for required workflow
  .github/linters/.markdownlint.yml
  .github/super-linter.env
  .github/workflows/test-pull-request.yml
  .markdownlint.yml
  package.json
Labels: maintenance

#101 Remove reference info for Checkout schema
  .github/super-linter.env
  package.json
  src/pages/graphql/schema/checkout/index.md
  src/pages/graphql/schema/checkout/mutations/create-braintree-client-token.md
  src/pages/graphql/schema/checkout/mutations/create-klarna-payments-session.md
  src/pages/graphql/schema/checkout/mutations/create-payflow-pro-token.md
  src/pages/graphql/schema/checkout/mutations/create-paypal-express-token.md
  src/pages/graphql/schema/checkout/mutations/delete-payment-token.md
  src/pages/graphql/schema/checkout/mutations/handle-payflow-pro-response.md
  src/pages/graphql/schema/checkout/mutations/index.md
  src/pages/graphql/schema/checkout/queries/agreements.md
  src/pages/graphql/schema/checkout/queries/customer-payment-tokens.md
  src/pages/graphql/schema/checkout/queries/get-hosted-pro-url.md
  src/pages/graphql/schema/checkout/queries/get-payflow-link-token.md
  src/pages/graphql/schema/checkout/queries/index.md
  yarn.lock
Labels: maintenance

#102 [MSRCH-2569] Added category examples to Live Search productSearch topic
  src/pages/graphql/schema/live-search/queries/product-search.md
Labels: major update, 2.4.6

#104 Change indexing cron to monthly
  .github/workflows/index.yml
Labels: maintenance

#108 Removing 2.4.5 schemas
  src/openapi/admin-schema-2.4.5.yaml
  src/openapi/customer-schema-2.4.5.yaml
  src/openapi/guest-schema-2.4.5.yaml
Labels: editorial, 2.4.6

#106 Update catalog-pricing.md
  src/pages/rest/modules/catalog/catalog-pricing.md
Labels: technical

#109 Fix spelling
  src/pages/graphql/develop/index.md
Labels: editorial

#112 fixing a typo
  src/pages/rest/tutorials/orders/order-create-customer.md
Labels: editorial

#110 Added swatch support to CS products ref
  src/pages/_includes/graphql/catalog-product-view.md
  src/pages/_includes/graphql/catalog-service/headers.md
  src/pages/_includes/graphql/catalog-service/product-view.md
  src/pages/graphql/schema/catalog-service/queries/products.md
Labels: major update, internal

#113 Fix naming of entered_options
  src/pages/graphql/schema/cart/mutations/add-products.md
Labels: technical, internal

#115 COMDOX-588: Standardized README
  README.md
Labels: maintenance
