Repository AdobeDocs/commerce-webapi, pull requests merged in 2023-09, with the labels that each got.

#191 LYNX-179: Documentation for order cancellation mutation
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/orders/mutations/cancel-order.md
  src/pages/graphql/schema/store/queries/store-config.md
Labels: new topic, internal, 2.4.7

#193 ACPT-1428: Create Import JSON API documentation
  src/pages/rest/modules/import/index.md
Labels: major update, internal, 2.4.7

#202 COMDOX-345: Remove duplicate remark config
  package.json
Labels: internal, maintenance

#200 Redocly intro text
  src/_includes/redocly-intro.md
  src/openapi/.redocly.yaml
  src/openapi/admin-schema-2.4.7-beta.yaml
  src/openapi/customer-schema-2.4.7-beta.yaml
  src/openapi/guest-schema-2.4.7-beta.yaml
Labels: editorial, internal

#203 COMDOX-570: Adding intro to `2.4.6` schemas
  src/openapi/admin-schema-2.4.6.yaml
  src/openapi/customer-schema-2.4.6.yaml
  src/openapi/guest-schema-2.4.6.yaml
Labels: editorial, internal

#209 Add EAV queries to list of cacheable queries
  src/_includes/graphql/cache/queries-247beta.md
Labels: technical, internal, 2.4.7

#208 ACP2E-2419: Document the updated behavior of isEmailAvailable endpoint in 2.4.7-b1
  src/pages/graphql/schema/customer/queries/is-email-available.md
Labels: technical, internal, 2.4.7

#211 Update is-email-available.md, the line break was missing between lines once the page has been published
  src/pages/graphql/schema/customer/queries/is-email-available.md
Labels: editorial, internal, 2.4.7

#199 ACP2E-2290: [CLARIFICATION] Hidden sections in Pagebuilder returned in GraphQL response
  src/pages/graphql/schema/store/queries/cms-blocks.md
  src/pages/graphql/schema/store/queries/cms-page.md
Labels: editorial, internal
