Repository AdobeDocs/commerce-webapi, pull requests merged in 2023-11, with the labels that each got.

#220 Fix indexing workflow
  .github/workflows/index.yml
Labels: bug, maintenance

#221 Update workflows with deployments
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#222 Migrate Services schemas
  src/_includes/graphql/catalog-service/categories.md
  src/_includes/graphql/catalog-service/headers.md
  src/_includes/graphql/catalog-service/product-view.md
  src/_includes/graphql/live-search-headers.md
  src/data/navigation/sections/graphql.js
  src/pages/graphql/index.md
  src/pages/graphql/schema/catalog-service/index.md
  src/pages/graphql/schema/catalog-service/queries/categories.md
  src/pages/graphql/schema/catalog-service/queries/index.md
  src/pages/graphql/schema/catalog-service/queries/product-search.md
  src/pages/graphql/schema/catalog-service/queries/products.md
  src/pages/graphql/schema/catalog-service/queries/refine-product.md
  src/pages/graphql/schema/index.md
  src/pages/graphql/schema/live-search/index.md
  src/pages/graphql/schema/live-search/queries/attribute-metadata.md
  src/pages/graphql/schema/live-search/queries/index.md
  src/pages/graphql/schema/live-search/queries/product-search.md
  src/pages/graphql/schema/product-recommendations/index.md
  src/pages/graphql/schema/product-recommendations/queries/index.md
  src/pages/graphql/schema/product-recommendations/queries/recommendations.md
Labels: migration, internal, maintenance

#224 GraphQL: Remove reference info from Company section
  src/pages/graphql/schema/b2b/company/index.md
  src/pages/graphql/schema/b2b/company/mutations/create-role.md
  src/pages/graphql/schema/b2b/company/mutations/create-team.md
  src/pages/graphql/schema/b2b/company/mutations/create-user.md
  src/pages/graphql/schema/b2b/company/mutations/create.md
  src/pages/graphql/schema/b2b/company/mutations/delete-role.md
  src/pages/graphql/schema/b2b/company/mutations/delete-team.md
  src/pages/graphql/schema/b2b/company/mutations/delete-user.md
  src/pages/graphql/schema/b2b/company/mutations/index.md
  src/pages/graphql/schema/b2b/company/mutations/update-role.md
  src/pages/graphql/schema/b2b/company/mutations/update-structure.md
  src/pages/graphql/schema/b2b/company/mutations/update-team.md
  src/pages/graphql/schema/b2b/company/mutations/update-user.md
  src/pages/graphql/schema/b2b/company/mutations/update.md
  src/pages/graphql/schema/b2b/company/queries/company.md
  src/pages/graphql/schema/b2b/company/queries/index.md
  src/pages/graphql/schema/b2b/company/queries/is-company-admin-email-available.md
  src/pages/graphql/schema/b2b/company/queries/is-company-email-available.md
  src/pages/graphql/schema/b2b/company/queries/is-company-role-name-available.md
  src/pages/graphql/schema/b2b/company/queries/is-company-user-email-available.md
  src/pages/graphql/schema/b2b/company/unions/index.md
  src/pages/graphql/schema/b2b/company/unions/structure-entity.md
Labels: internal, maintenance

#225 GraphQL: Remove reference info from Negotiable Quote section
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/b2b/negotiable-quote/index.md
  src/pages/graphql/schema/b2b/negotiable-quote/interfaces/address.md
  src/pages/graphql/schema/b2b/negotiable-quote/interfaces/index.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/close.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/delete.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/index.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/place-order.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/remove-items.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/request.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/send-for-review.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/set-billing-address.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/set-payment-method.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/set-shipping-address.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/set-shipping-methods.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/update-quantities.md
  src/pages/graphql/schema/b2b/negotiable-quote/queries/index.md
  src/pages/graphql/schema/b2b/negotiable-quote/queries/quote.md
  src/pages/graphql/schema/b2b/negotiable-quote/queries/quotes.md
  src/pages/graphql/schema/b2b/negotiable-quote/unions/index.md
Labels: internal, maintenance

#226 GraphQL: Remove reference info from purchase order/po rules sections
  src/pages/graphql/schema/b2b/purchase-order-rule/interfaces/index.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/create.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/delete.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/index.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/update.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/validate.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/add-comment.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/add-items-to-cart.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/approve.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/cancel.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/index.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/place-order.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/place-purchase-order.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/reject.md
Labels: internal, maintenance

#227 GraphQL: Remove reference info from requisition list section
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/b2b/requisition-list/index.md
  src/pages/graphql/schema/b2b/requisition-list/interfaces/index.md
  src/pages/graphql/schema/b2b/requisition-list/interfaces/item.md
  src/pages/graphql/schema/b2b/requisition-list/mutations/add-items-to-cart.md
  src/pages/graphql/schema/b2b/requisition-list/mutations/add-products.md
  src/pages/graphql/schema/b2b/requisition-list/mutations/clear-customer-cart.md
  src/pages/graphql/schema/b2b/requisition-list/mutations/copy-items.md
  src/pages/graphql/schema/b2b/requisition-list/mutations/create.md
  src/pages/graphql/schema/b2b/requisition-list/mutations/delete-items.md
  src/pages/graphql/schema/b2b/requisition-list/mutations/delete.md
  src/pages/graphql/schema/b2b/requisition-list/mutations/index.md
  src/pages/graphql/schema/b2b/requisition-list/mutations/move-items.md
  src/pages/graphql/schema/b2b/requisition-list/mutations/update-items.md
  src/pages/graphql/schema/b2b/requisition-list/mutations/update.md
Labels: internal, maintenance

#230 Update REST API metadata
  src/data/navigation/sections/rest.js
  src/pages/rest/index.md
  src/pages/rest/quick-reference/index.md
Labels: editorial, internal

#236 GraphQL: Remove reference info from Cart section
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/cart/index.md
  src/pages/graphql/schema/cart/interfaces/cart-item.md
  src/pages/graphql/schema/cart/interfaces/index.md
  src/pages/graphql/schema/cart/mutations/add-bundle-products.md
  src/pages/graphql/schema/cart/mutations/add-configurable-products.md
  src/pages/graphql/schema/cart/mutations/add-downloadable-products.md
  src/pages/graphql/schema/cart/mutations/add-products.md
  src/pages/graphql/schema/cart/mutations/add-simple-products.md
  src/pages/graphql/schema/cart/mutations/add-virtual-products.md
  src/pages/graphql/schema/cart/mutations/apply-coupon.md
  src/pages/graphql/schema/cart/mutations/apply-giftcard.md
  src/pages/graphql/schema/cart/mutations/apply-reward-points.md
  src/pages/graphql/schema/cart/mutations/apply-store-credit.md
  src/pages/graphql/schema/cart/mutations/assign-customer-to-guest-cart.md
  src/pages/graphql/schema/cart/mutations/create-empty-cart.md
  src/pages/graphql/schema/cart/mutations/index.md
  src/pages/graphql/schema/cart/mutations/merge.md
  src/pages/graphql/schema/cart/mutations/place-order.md
  src/pages/graphql/schema/cart/mutations/remove-coupon.md
  src/pages/graphql/schema/cart/mutations/remove-giftcard.md
  src/pages/graphql/schema/cart/mutations/remove-item.md
  src/pages/graphql/schema/cart/mutations/remove-reward-points.md
  src/pages/graphql/schema/cart/mutations/remove-store-credit.md
  src/pages/graphql/schema/cart/mutations/set-billing-address.md
  src/pages/graphql/schema/cart/mutations/set-gift-options.md
  src/pages/graphql/schema/cart/mutations/set-guest-email.md
  src/pages/graphql/schema/cart/mutations/set-payment-method.md
  src/pages/graphql/schema/cart/mutations/set-payment-place-order.md
  src/pages/graphql/schema/cart/mutations/set-shipping-address.md
  src/pages/graphql/schema/cart/mutations/set-shipping-method.md
  src/pages/graphql/schema/cart/mutations/update-items.md
  src/pages/graphql/schema/cart/queries/cart.md
  src/pages/graphql/schema/cart/queries/index.md
  src/pages/graphql/schema/cart/queries/pickup-locations.md
Labels: internal, maintenance

#223 Sync deployment workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#237 GraphQL: Remove reference info from Attributes section
  src/pages/graphql/schema/attributes/index.md
  src/pages/graphql/schema/attributes/queries/attributes-form.md
  src/pages/graphql/schema/attributes/queries/attributes-list.md
  src/pages/graphql/schema/attributes/queries/custom-attribute-metadata-v2.md
  src/pages/graphql/schema/attributes/queries/custom-attribute-metadata.md
  src/pages/graphql/schema/attributes/queries/index.md
Labels: internal, maintenance

#238 Add core versions to graphql API ref TOC
  src/data/navigation/sections/graphql.js
Labels: editorial, internal

#244 GraphQL: Remove reference info from PWA schema
  src/_includes/graphql/notes/beta-pwa.md
  src/pages/graphql/schema/attributes/queries/attributes-metadata.md
  src/pages/graphql/schema/store/mutations/contact-us.md
  src/pages/graphql/schema/store/queries/dynamic-blocks.md
  src/pages/graphql/schema/store/queries/recaptcha-v3-config.md
Labels: internal, maintenance

#246 GraphQL: Remove unused include files
  src/_includes/graphql/cart-address-input-24.md
  src/_includes/graphql/cart-item-input-24.md
  src/_includes/graphql/cart-object-24.md
  src/_includes/graphql/cart-user-input-errors.md
  src/_includes/graphql/catalog-service-headers.md
  src/_includes/graphql/category-filter-input.md
  src/_includes/graphql/cms-block-object.md
  src/_includes/graphql/company-role.md
  src/_includes/graphql/company-team.md
  src/_includes/graphql/company.md
  src/_includes/graphql/compare-list-output.md
  src/_includes/graphql/country-output.md
  src/_includes/graphql/create-customer.md
  src/_includes/graphql/credit-memo-item-interface.md
  src/_includes/graphql/customer-address-input-24.md
  src/_includes/graphql/customer-address-output-24.md
  src/_includes/graphql/customer-orders-output.md
  src/_includes/graphql/customer-output-24.md
  src/_includes/graphql/customer-output.md
  src/_includes/graphql/customer-payment-tokens.md
  src/_includes/graphql/customizable-option-input-24.md
  src/_includes/graphql/customizable-option-input.md
  src/_includes/graphql/downloadable-items-links.md
  src/_includes/graphql/entered-option-input.md
  src/_includes/graphql/examples/grouped-product-sample-24.md
  src/_includes/graphql/gift-card-item.md
  src/_includes/graphql/gift-message.md
  src/_includes/graphql/gift-registry-dynamic-attribute-metadata-interface.md
  src/_includes/graphql/gift-registry-dynamic-interface.md
  src/_includes/graphql/gift-registry-items-user-error.md
  src/_includes/graphql/gift-registry-search-result.md
  src/_includes/graphql/gift-registry.md
  src/_includes/graphql/gift-wrapping.md
  src/_includes/graphql/invoice-item-interface.md
  src/_includes/graphql/item-selected-bundle-option.md
  src/_includes/graphql/negotiable-quote-address-input.md
  src/_includes/graphql/negotiable-quote.md
  src/_includes/graphql/negotiable-quotes-input.md
  src/_includes/graphql/order-item-interface.md
  src/_includes/graphql/product-review.md
  src/_includes/graphql/quote-payment-input.md
  src/_includes/graphql/requisition-list.md
  src/_includes/graphql/return.md
  src/_includes/graphql/routable-interface.md
  src/_includes/graphql/shipment-item-interface.md
  src/_includes/graphql/store-config.md
  src/_includes/graphql/wishlist-item-interface.md
  src/_includes/graphql/wishlist-user-input-errors.md
  src/_includes/graphql/wishlist.md
  src/pages/graphql/schema/b2b/negotiable-quote/mutations/delete.md
  src/pages/graphql/schema/gift-registry/queries/types.md
  src/pages/graphql/schema/products/interfaces/types/grouped.md
  src/pages/graphql/schema/products/interfaces/types/index.md
Labels: internal, maintenance

#245 Add a remark plugin to support custom header id
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: enhancement

#248 Update theme and caniuse-lite
  package.json
  yarn.lock
Labels: dependencies

#247 COMDOX-857: Remove link check ignore pattern and add new glob pattern for frontmatter check
  .remarkrc.mjs
  package.json
  src/pages/graphql/schema/b2b/purchase-order-rule/index.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/delete.md
  src/pages/graphql/schema/b2b/purchase-order-rule/mutations/update.md
  src/pages/graphql/schema/b2b/purchase-order/index.md
  src/pages/graphql/schema/cart/mutations/remove-item.md
  src/pages/graphql/schema/cart/queries/cart.md
  src/pages/graphql/schema/checkout/mutations/create-klarna-payments-session.md
  src/pages/graphql/schema/products/interfaces/attributes.md
  src/pages/graphql/schema/products/interfaces/index.md
  src/pages/graphql/schema/products/interfaces/pwa-implementations.md
  src/pages/graphql/schema/products/interfaces/routable.md
  src/pages/graphql/schema/store/queries/index.md
Labels: maintenance

#249 Update README.md
  README.md
Labels: editorial, internal
