Repository AdobeDocs/commerce-webapi, pull requests merged in 2024-03, with the labels that each got.

#289 LYNX-325: Documentation for createGuestCart
  src/pages/graphql/schema/cart/mutations/create-empty-cart.md
  src/pages/graphql/schema/cart/mutations/create-guest-cart.md
  src/pages/graphql/tutorials/checkout/create-cart.md
Labels: new-topic, internal

#295 Fixed typo in a URL
  src/pages/graphql/schema/checkout/index.md
Labels: editorial, internal

#282 PAY-5085: Updates GraphQL for Payment Services with GooglePay details
  src/pages/graphql/payment-services/index.md
  src/pages/graphql/schema/checkout/mutations/create-payment-order.md
  src/pages/graphql/schema/checkout/queries/get-payment-config.md
  src/pages/graphql/schema/checkout/queries/get-payment-sdk.md
Labels: major-update

#305 LYNX-375: Add doc of the token expiration config
  src/pages/graphql/schema/store/queries/store-config.md
Labels: major-update, 2.4.7

#286 LYNX-374: Added new confirm-email mutation
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/customer/mutations/confirm-email.md
  src/pages/graphql/schema/customer/mutations/index.md
Labels: new-topic, internal

#296 LYNX-220: Added multicoupon documentation
  src/pages/graphql/schema/cart/mutations/apply-coupons.md
  src/pages/graphql/schema/cart/mutations/remove-coupons.md
  src/pages/rest/modules/multicoupon/index.md
Labels: new-topic, internal, 2.4.7

#297 LYNX-327: Added ClearCart mutation
  src/pages/graphql/schema/cart/mutations/clear-cart.md
  src/pages/graphql/schema/cart/mutations/index.md
Labels: new-topic, internal

#299 LYNX-329: Updated examples returning cart items field to use itemsV2
  src/pages/graphql/schema/cart/interfaces/index.md
  src/pages/graphql/schema/cart/mutations/add-bundle-products.md
  src/pages/graphql/schema/cart/mutations/add-configurable-products.md
  src/pages/graphql/schema/cart/mutations/add-downloadable-products.md
  src/pages/graphql/schema/cart/mutations/add-products.md
  src/pages/graphql/schema/cart/mutations/add-simple-products.md
  src/pages/graphql/schema/cart/mutations/add-virtual-products.md
  src/pages/graphql/schema/cart/mutations/apply-coupon.md
  src/pages/graphql/schema/cart/mutations/apply-reward-points.md
  src/pages/graphql/schema/cart/mutations/assign-customer-to-guest-cart.md
  src/pages/graphql/schema/cart/mutations/merge.md
  src/pages/graphql/schema/cart/mutations/remove-coupon.md
  src/pages/graphql/schema/cart/mutations/remove-item.md
  src/pages/graphql/schema/cart/mutations/set-gift-options.md
  src/pages/graphql/schema/cart/mutations/update-items.md
  src/pages/graphql/schema/cart/queries/cart.md
  src/pages/graphql/schema/orders/mutations/reorder-items.md
Labels: major-update, internal, 2.4.7

#300 LYNX-332: change attributeForm note
  src/pages/graphql/schema/attributes/queries/attributes-form.md
Labels: editorial, internal, 2.4.7

#301 LYNX-335: estimateTotals mutation documentation
  src/pages/graphql/schema/cart/mutations/estimate-totals.md
  src/pages/graphql/schema/cart/mutations/index.md
Labels: new-topic, internal, 2.4.7

#302 LYNX-385: documentation for estimateShippingMethods mutation
  src/pages/graphql/schema/cart/mutations/estimate-shipping-methods.md
  src/pages/graphql/schema/cart/mutations/index.md
Labels: new-topic, internal, 2.4.7

#303 LYNX-328: Add Status codes and GraphQL responses page to Usage section
  src/pages/graphql/schema/store/queries/store-config.md
  src/pages/graphql/usage/api-response.md
  src/pages/graphql/usage/authorization-tokens.md
Labels: new-topic, internal, 2.4.7

#308 Add navigation for new topic
  src/data/navigation/sections/graphql.js
Labels: internal, maintenance

#196 ACP2E-2119: update documentation with new added attribute and examples.
  src/pages/graphql/schema/products/queries/products.md
Labels: major-update, internal, 2.4.7
