Repository AdobeDocs/commerce-webapi, pull requests merged in 2024-12, with the labels that each got.

#387 Update workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
  package.json
  src/pages/rest/tutorials/inventory/run-ssa.md
Labels: maintenance

#386 PAY-5702: Adds docs for the updated vault feature in Payment Services
  src/data/navigation/sections/graphql.js
  src/pages/graphql/payment-methods/index.md
  src/pages/graphql/payment-services-extension/index.md
  src/pages/graphql/payment-services-extension/mutations/create-payment-order.md
  src/pages/graphql/payment-services-extension/mutations/create-vault-card-payment-token.md
  src/pages/graphql/payment-services-extension/mutations/create-vault-card-setup-token.md
  src/pages/graphql/payment-services-extension/mutations/sync-payment-order.md
  src/pages/graphql/payment-services-extension/queries/get-payment-config.md
  src/pages/graphql/payment-services-extension/queries/get-payment-order.md
  src/pages/graphql/payment-services-extension/queries/get-payment-sdk.md
  src/pages/graphql/payment-services-extension/queries/get-vault-config.md
  src/pages/graphql/payment-services-extension/workflows/checkout.md
  src/pages/graphql/payment-services-extension/workflows/minicart.md
  src/pages/graphql/payment-services-extension/workflows/vault.md
  src/pages/graphql/schema/checkout/index.md
  src/pages/graphql/schema/checkout/mutations/index.md
  src/pages/graphql/schema/checkout/queries/index.md
Labels: enhancement

#389 Add navigation for returns mutations
  src/data/navigation/sections/graphql.js
Labels: editorial, internal

#390 Adds index files to the new Payment Services Extension folder and subfolders in GraphQL docs
  src/data/navigation/sections/graphql.js
  src/pages/graphql/payment-methods/index.md
  src/pages/graphql/payment-services-extension/index.md
  src/pages/graphql/payment-services-extension/mutations/index.md
  src/pages/graphql/payment-services-extension/queries/index.md
  src/pages/graphql/payment-services-extension/workflows/index.md
Labels: enhancement
