Repository AdobeDocs/commerce-webapi, pull requests merged in 2024-07, with the labels that each got.

#338 Upgrade devDependencies
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: dependencies

#335 Add natural language linting
  .github/linters/.textlintrc
  .github/super-linter.env
  .github/workflows/test-pull-request.yml
  .textlintrc
  README.md
  src/_includes/graphql/payment-methods/payflow-link-workflow.md
  src/pages/get-started/api-security.md
  src/pages/get-started/authentication/gs-authentication-oauth.md
  src/pages/get-started/authentication/gs-authentication-session.md
  src/pages/get-started/gs-curl.md
  src/pages/get-started/index.md
  src/pages/get-started/rate-limiting.md
  src/pages/get-started/web-api-functional-testing.md
  src/pages/graphql/develop/debugging.md
  src/pages/graphql/develop/functional-testing.md
  src/pages/graphql/release-notes.md
  src/pages/graphql/schema/cart/mutations/apply-coupon.md
  src/pages/graphql/schema/cart/mutations/apply-coupons.md
  src/pages/graphql/schema/cart/mutations/apply-giftcard.md
  src/pages/graphql/schema/cart/queries/cart.md
  src/pages/graphql/schema/checkout/mutations/create-braintree-client-token.md
  src/pages/graphql/schema/checkout/mutations/create-klarna-payments-session.md
  src/pages/graphql/schema/checkout/mutations/create-payflow-pro-token.md
  src/pages/graphql/schema/checkout/mutations/handle-payflow-pro-response.md
  src/pages/graphql/schema/checkout/queries/get-payflow-link-token.md
  src/pages/graphql/schema/checkout/queries/get-payment-sdk.md
  src/pages/graphql/schema/gift-registry/mutations/update-registrants.md
  src/pages/graphql/schema/products/interfaces/pwa-implementations.md
  src/pages/graphql/schema/products/interfaces/types/configurable.md
  src/pages/graphql/schema/products/queries/products.md
  src/pages/graphql/tutorials/checkout/index.md
  src/pages/graphql/usage/api-response.md
  src/pages/graphql/usage/caching.md
  src/pages/graphql/usage/custom-filters.md
  src/pages/graphql/usage/index.md
  src/pages/rest/b2b/company-object.md
  src/pages/rest/b2b/negotiable-quote.md
  src/pages/rest/inventory/index.md
  src/pages/rest/tutorials/bulk-configurable-product/plan-product.md
  src/pages/rest/tutorials/configurable-product/plan-product.md
  src/pages/rest/tutorials/index.md
  src/pages/rest/tutorials/orders/order-admin-token.md
  src/pages/rest/tutorials/orders/order-create-shipment.md
  src/pages/rest/tutorials/orders/order-issue-refund.md
Labels: enhancement, editorial

#343 Enable indexing on deploy
  .github/workflows/index.yml
  .github/workflows/publish.yml
Labels: internal, maintenance

#341 ACPF-295: Add recommendations for managing message queues and consumers
  src/pages/rest/use-rest/bulk-endpoints.md
Labels: editorial, internal
