Repository AdobeDocs/commerce-webapi, pull requests merged in 2024-04, with the labels that each got.

#312 Add links to SpectaQL docs
  src/data/navigation/sections/graphql.js
  src/data/navigation/sections/rest.js
  src/pages/graphql/schema/cart/mutations/clear-cart.md
  src/pages/graphql/schema/cart/mutations/create-guest-cart.md
  src/pages/graphql/schema/cart/mutations/estimate-shipping-methods.md
  src/pages/graphql/schema/cart/mutations/estimate-totals.md
  src/pages/graphql/schema/customer/mutations/confirm-email.md
Labels: maintenance, 2.4.7

#314 clearCart is Commerce-only
  src/pages/graphql/schema/cart/mutations/clear-cart.md
Labels: editorial, internal, 2.4.7

#304 LYNX-334: Add doc for place order changes and new queries
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/cart/mutations/place-order.md
  src/pages/graphql/schema/orders/queries/guest-order-by-token.md
  src/pages/graphql/schema/orders/queries/guest-order.md
  src/pages/graphql/schema/orders/queries/index.md
  src/pages/graphql/tutorials/checkout/place-order.md
Labels: new-topic, internal, 2.4.7

#313 Upgrade theme to v4.11.9
  package.json
  yarn.lock
Labels: dependencies, internal

#287 LYNX-376: Documentation for recaptchaFormConfig query
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/store/queries/index.md
  src/pages/graphql/schema/store/queries/recaptcha-form-config.md
Labels: new-topic, internal

#315 Updates to multicoupon
  src/pages/rest/modules/multicoupon/index.md
Labels: editorial, 2.4.7

#318 Add UTF-8 info
  src/pages/rest/modules/import/index.md
Labels: editorial, internal, 2.4.7

#325 Editorial fixes for the home page
  src/pages/get-started/gs-web-api-request.md
  src/pages/graphql/payment-methods/klarna.md
  src/pages/index.md
Labels: editorial, internal

#307 ACP2E-2872: [Documentation] Update documentation regarding Bundle pro…
  src/data/navigation/sections/rest.js
  src/pages/rest/tutorials/bundle-product/update-options-and-links.md
Labels: new-topic, internal
