Repository AdobeDocs/commerce-webapi, pull requests merged in 2024-01, with the labels that each got.

#271 Fix note formatting
  src/pages/rest/tutorials/bulk-configurable-product/create-configurable-simple-products.md
Labels: editorial, internal

#276 GH-274: Fix typo
  src/pages/rest/tutorials/bundle-product/create-bundle-product.md
Labels: editorial, internal

#275 Remove note that Authentification header is required.
  src/pages/graphql/schema/b2b/company/mutations/create.md
Labels: technical

#277 Revert the PR testing workflow
  .github/workflows/test-pull-request.yml
Labels: maintenance

#280 Upgrade theme to v4.11.3
  package.json
  yarn.lock
Labels: dependencies, internal
