Repository AdobeDocs/commerce-webapi, pull requests merged in 2024-08, with the labels that each got.

#345 Add Commerce-only tag to import topic
  src/pages/rest/modules/import/index.md
Labels: editorial, internal

#349 Revert "COMDOX-840: Redesign Feedback component"
  src/@adobe/gatsby-theme-aio/components/MDXFilter/index.js
  src/@adobe/gatsby-theme-aio/conf/globals.js
Labels: internal, maintenance

#350 Update order-admin-token.md
  src/pages/rest/tutorials/orders/order-admin-token.md
Labels: editorial

#353 fixing code block
  src/pages/rest/tutorials/bulk-configurable-product/create-configurable-simple-products.md
Labels: editorial, internal

#354 Refactor GitHub workflows
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
Labels: maintenance

#356 Fix natural language linting errors
  .github/CODE_OF_CONDUCT.md
  .github/linters/.textlintrc
  README.md
  src/pages/graphql/schema/checkout/mutations/create-payment-order.md
  src/pages/graphql/schema/checkout/queries/get-payment-config.md
  src/pages/graphql/schema/products/queries/url-resolver.md
  src/pages/graphql/schema/store/queries/country.md
  src/pages/graphql/tutorials/checkout/create-cart.md
  src/pages/graphql/usage/security-configuration.md
  src/pages/rest/b2b/company-structures.md
  src/pages/rest/use-rest/anonymous-api-security.md
Labels: editorial, internal
