Repository AdobeDocs/commerce-webapi, pull requests merged in 2024-10, with the labels that each got.

#364 Update place-purchase-order.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/place-order.md
  src/pages/graphql/schema/b2b/purchase-order/mutations/place-purchase-order.md
Labels: enhancement, editorial

#367 Review and update WepApi functional documentation
  src/pages/graphql/develop/functional-testing.md
Labels: technical, internal

#371 Replace links to decommissioned resources
  src/pages/get-started/api-security.md
  src/pages/graphql/schema/cart/mutations/set-payment-place-order.md
  src/pages/graphql/schema/checkout/mutations/create-braintree-client-token.md
  src/pages/graphql/schema/store/queries/dynamic-blocks.md
  src/pages/graphql/tutorials/checkout/apply-coupon.md
  src/pages/graphql/tutorials/checkout/index.md
  src/pages/graphql/usage/caching.md
  src/pages/graphql/usage/staging-queries.md
  src/pages/rest/b2b/index.md
  src/pages/rest/inventory/manage-source-items.md
  src/pages/rest/modules/import/index.md
  src/pages/rest/tutorials/index.md
  src/pages/rest/tutorials/orders/index.md
Labels: editorial
