Repository AdobeDocs/commerce-webapi, pull requests merged in 2025-02, with the labels that each got.

#397 add external link to toc
  src/data/navigation/sections/graphql.js
Labels: editorial

#365 Update create-guest-cart.md
  src/pages/graphql/schema/cart/mutations/create-guest-cart.md
Labels: editorial

#403 Update GitHub workflows
  .github/workflows/github-pages.yml
Labels: internal, maintenance

#404 Convert test-pull-request workflow to reusable
  .github/workflows/test-pull-request.yml
Labels: maintenance

#402 LYNX-679: Added documentation for new queries
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/cart/queries/all-rules.md
  src/pages/graphql/schema/cart/queries/index.md
  src/pages/graphql/schema/customer/queries/all-groups.md
  src/pages/graphql/schema/customer/queries/all-segments.md
  src/pages/graphql/schema/customer/queries/index.md
  src/pages/graphql/schema/customer/queries/segments.md
  src/pages/graphql/schema/products/queries/all-rules.md
  src/pages/graphql/schema/products/queries/index.md
Labels: new-topic, internal
