Repository AdobeDocs/commerce-webapi, pull requests merged in 2025-04, with the labels that each got.

#414 Update REST endpoint summary reference for Adobe Commerce B2B
  src/pages/rest/b2b/integrations.md
Labels: technical, editorial, 2.4.7

#409 Remove 2.4.8 beta notices
  src/pages/get-started/api-security.md
  src/pages/graphql/payment-services-extension/mutations/create-payment-order.md
  src/pages/graphql/payment-services-extension/mutations/create-vault-card-payment-token.md
  src/pages/graphql/payment-services-extension/mutations/create-vault-card-setup-token.md
  src/pages/graphql/payment-services-extension/mutations/sync-payment-order.md
  src/pages/graphql/payment-services-extension/queries/get-payment-config.md
  src/pages/graphql/payment-services-extension/queries/get-payment-order.md
  src/pages/graphql/payment-services-extension/queries/get-payment-sdk.md
  src/pages/graphql/payment-services-extension/queries/get-vault-config.md
  src/pages/graphql/schema/cart/queries/all-rules.md
  src/pages/graphql/schema/customer/queries/all-groups.md
  src/pages/graphql/schema/customer/queries/all-segments.md
  src/pages/graphql/schema/customer/queries/segments.md
  src/pages/graphql/schema/orders/mutations/confirm-return.md
  src/pages/graphql/schema/orders/mutations/request-guest-return.md
  src/pages/graphql/schema/products/queries/all-rules.md
Labels: editorial, internal, 2.4.8

#417 Fix BIC link
  src/pages/graphql/schema/customer/queries/is-email-available.md
Labels: editorial
