Repository AdobeDocs/commerce-webapi, pull requests merged in 2025-06, with the labels that each got.

#435 ACP2E-3957: [Documentation] Update documentation regarding X-Magento-Cache-Id in graphQL mutation requests
  src/pages/graphql/usage/caching.md
Labels: technical, internal

#440 Remove duplicated note
  src/pages/graphql/usage/caching.md
Labels: editorial

#441 Add mutations for custom attributes
  src/_includes/custom-attribute-installation.md
  src/_includes/graphql/custom-attribute-availability.md
  src/data/navigation/sections/graphql.js
  src/data/navigation/sections/rest.js
  src/pages/graphql/schema/attributes/index.md
  src/pages/graphql/schema/attributes/mutations/index.md
  src/pages/graphql/schema/attributes/mutations/set-custom-cart-item.md
  src/pages/graphql/schema/attributes/mutations/set-custom-cart.md
  src/pages/graphql/schema/attributes/mutations/set-custom-company.md
  src/pages/graphql/schema/attributes/mutations/set-custom-credit-memo-item.md
  src/pages/graphql/schema/attributes/mutations/set-custom-credit-memo.md
  src/pages/graphql/schema/attributes/mutations/set-custom-invoice-item.md
  src/pages/graphql/schema/attributes/mutations/set-custom-invoice.md
  src/pages/graphql/schema/attributes/mutations/set-custom-negotiable-quote.md
  src/pages/rest/modules/custom-attributes.md
  src/pages/rest/modules/index.md
Labels: new-topic, internal

#444 Move Services queries back to webapi
  src/_includes/graphql/catalog-service/categories.md
  src/_includes/graphql/catalog-service/headers.md
  src/_includes/graphql/catalog-service/product-view.md
  src/_includes/graphql/customer-group-code.md
  src/_includes/graphql/endpoints.md
  src/_includes/graphql/live-search-headers.md
  src/data/navigation/sections/graphql.js
  src/pages/graphql/index.md
  src/pages/graphql/schema/catalog-service/index.md
  src/pages/graphql/schema/catalog-service/queries/categories.md
  src/pages/graphql/schema/catalog-service/queries/index.md
  src/pages/graphql/schema/catalog-service/queries/product-variants.md
  src/pages/graphql/schema/catalog-service/queries/products.md
  src/pages/graphql/schema/catalog-service/queries/refine-product.md
  src/pages/graphql/schema/index.md
  src/pages/graphql/schema/live-search/index.md
  src/pages/graphql/schema/live-search/queries/attribute-metadata.md
  src/pages/graphql/schema/live-search/queries/index.md
  src/pages/graphql/schema/live-search/queries/product-search.md
  src/pages/graphql/schema/product-recommendations/index.md
  src/pages/graphql/schema/product-recommendations/queries/index.md
  src/pages/graphql/schema/product-recommendations/queries/recommendations.md
  src/pages/graphql/schema/products/queries/categories.md
  src/pages/graphql/schema/products/queries/products.md
Labels: internal, maintenance

#443 Fix highlighting error
  src/pages/rest/modules/custom-attributes.md
Labels: editorial, internal

#450 Remove old schema pages
  src/pages/graphql/reference/2.4.6/index.md
  src/pages/graphql/reference/2.4.7/index.md
  src/pages/graphql/reference/2.4.8/index.md
  src/pages/graphql/reference/index.md
  src/pages/index.md
  src/pages/reference/graphql/2.4.6/index.md
  src/pages/reference/graphql/2.4.7/index.md
  src/pages/reference/graphql/2.4.8/index.md
  src/pages/reference/graphql/saas/index.md
  src/pages/reference/rest/paas.md
  src/pages/reference/rest/saas.md
  src/pages/rest/quick-reference/index.md
  src/pages/rest/reference/index.md
  src/pages/rest/tutorials/index.md
  src/pages/rest/tutorials/inventory/index.md
  src/pages/rest/tutorials/orders/index.md
  src/pages/rest/tutorials/orders/order-issue-refund.md
Labels: editorial

#452 Add routes for ACCS Async/bulk REST APIs
  src/pages/rest/use-rest/asynchronous-web-endpoints.md
  src/pages/rest/use-rest/bulk-endpoints.md
  src/pages/rest/use-rest/operation-status-endpoints.md
  src/pages/rest/use-rest/operation-status-search.md
Labels: technical, internal

#451 removed ACCS early access message
  src/pages/rest/authentication/index.md
Labels: maintenance
