Repository AdobeDocs/commerce-webapi, pull requests merged in 2025-05, with the labels that each got.

#419 Disable external link checking
  .remarkrc.mjs
  .remarkrc.yaml
  package.json
  yarn.lock
Labels: internal, maintenance

#421 LYNX-849: Documentation | Remove customer group/segments/promo rules information GraphQL from docs
  src/data/navigation/sections/graphql.js
  src/pages/graphql/schema/cart/queries/all-rules.md
  src/pages/graphql/schema/cart/queries/index.md
  src/pages/graphql/schema/customer/queries/all-groups.md
  src/pages/graphql/schema/customer/queries/all-segments.md
  src/pages/graphql/schema/customer/queries/index.md
  src/pages/graphql/schema/customer/queries/segments.md
  src/pages/graphql/schema/products/queries/all-rules.md
  src/pages/graphql/schema/products/queries/index.md
Labels: editorial, internal, 2.4.8

#424 More PaaS-only queries and mutations
  src/pages/graphql/payment-methods/hosted-pro.md
  src/pages/graphql/payment-methods/klarna.md
  src/pages/graphql/payment-methods/payflow-express.md
  src/pages/graphql/payment-methods/payflow-link.md
  src/pages/graphql/payment-methods/payflow-pro.md
  src/pages/graphql/schema/cart/mutations/add-downloadable-products.md
  src/pages/graphql/schema/cart/mutations/clear-cart.md
  src/pages/graphql/schema/checkout/mutations/create-klarna-payments-session.md
  src/pages/graphql/schema/checkout/mutations/create-payflow-pro-token.md
  src/pages/graphql/schema/checkout/mutations/create-paypal-express-token.md
  src/pages/graphql/schema/checkout/mutations/handle-payflow-pro-response.md
  src/pages/graphql/schema/checkout/queries/get-hosted-pro-url.md
  src/pages/graphql/schema/checkout/queries/get-payflow-link-token.md
  src/pages/graphql/schema/customer/mutations/send-email-to-friend.md
  src/pages/graphql/schema/customer/mutations/subscribe-email-to-newsletter.md
  src/pages/graphql/schema/customer/queries/downloadable-products.md
  src/pages/graphql/schema/products/mutations/create-review.md
  src/pages/graphql/schema/products/queries/product-review-ratings-metadata.md
  src/pages/graphql/schema/products/queries/products.md
  src/pages/graphql/schema/products/queries/route.md
  src/pages/graphql/schema/products/queries/url-resolver.md
  src/pages/graphql/schema/store/mutations/contact-us.md
  src/pages/graphql/schema/store/queries/cms-blocks.md
  src/pages/graphql/schema/store/queries/cms-page.md
  src/pages/graphql/schema/store/queries/dynamic-blocks.md
  src/pages/graphql/usage/staging-queries.md
Labels: internal, maintenance

#425 Fix: analytics tracking
  gatsby-browser.js
Labels: internal, maintenance

#426 Remove PaaS badge from contactUs query
  src/pages/graphql/schema/store/mutations/contact-us.md
Labels: technical, internal

#429 Mark PAAS-only REST content
  src/data/navigation/sections/rest.js
  src/pages/rest/attributes.md
  src/pages/rest/b2b/company-users.md
  src/pages/rest/b2b/company.md
  src/pages/rest/b2b/index.md
  src/pages/rest/b2b/negotiable-checkout.md
  src/pages/rest/b2b/negotiable-order-workflow.md
  src/pages/rest/inventory/in-store-pickup.md
  src/pages/rest/modules/catalog/index.md
  src/pages/rest/modules/import/index.md
  src/pages/rest/quick-reference/generate-local.md
  src/pages/rest/tutorials/index.md
  src/pages/rest/tutorials/inventory/assign-source-to-stock.md
  src/pages/rest/tutorials/inventory/bulk-transfer-products.md
  src/pages/rest/tutorials/inventory/configure-environment.md
  src/pages/rest/tutorials/inventory/create-cart-add-products.md
  src/pages/rest/tutorials/inventory/create-customer.md
  src/pages/rest/tutorials/inventory/create-invoice.md
  src/pages/rest/tutorials/inventory/create-order.md
  src/pages/rest/tutorials/inventory/create-shipment.md
  src/pages/rest/tutorials/inventory/create-sources.md
  src/pages/rest/tutorials/inventory/create-stock.md
  src/pages/rest/tutorials/inventory/in-store-pickup.md
  src/pages/rest/tutorials/inventory/index.md
  src/pages/rest/tutorials/inventory/prepare-for-checkout.md
  src/pages/rest/tutorials/inventory/reassign-products-to-another-source.md
  src/pages/rest/tutorials/inventory/run-ssa.md
  src/pages/rest/tutorials/orders/index.md
  src/pages/rest/tutorials/orders/order-add-items.md
  src/pages/rest/tutorials/orders/order-admin-token.md
  src/pages/rest/tutorials/orders/order-config-store.md
  src/pages/rest/tutorials/orders/order-create-customer.md
  src/pages/rest/tutorials/orders/order-create-invoice.md
  src/pages/rest/tutorials/orders/order-create-order.md
  src/pages/rest/tutorials/orders/order-create-quote.md
  src/pages/rest/tutorials/orders/order-create-shipment.md
  src/pages/rest/tutorials/orders/order-issue-refund.md
  src/pages/rest/tutorials/orders/order-prepare-checkout.md
  src/pages/rest/use-rest/anonymous-api-security.md
  src/pages/rest/use-rest/index.md
  src/pages/rest/use-rest/notes.md
  src/pages/rest/use-rest/performing-searches.md
  src/pages/rest/use-rest/protected-endpoints.md
  src/pages/rest/use-rest/search-endpoint.md
Labels: maintenance

#430 Mark topics as PaaS only in Getting Started
  src/pages/get-started/api-security.md
  src/pages/get-started/authentication/gs-authentication-oauth.md
  src/pages/get-started/authentication/gs-authentication-session.md
  src/pages/get-started/authentication/gs-authentication-token.md
  src/pages/get-started/authentication/index.md
  src/pages/get-started/create-integration.md
  src/pages/get-started/gs-curl.md
  src/pages/get-started/gs-web-api-request.md
  src/pages/get-started/rate-limiting.md
  src/pages/get-started/soap-web-api-calls.md
  src/pages/get-started/web-api-functional-testing.md
Labels: maintenance

#431 Re-enable subscribeEmailToNewsletter mutation for SaaS
  src/pages/graphql/schema/customer/mutations/subscribe-email-to-newsletter.md
Labels: internal, maintenance

#433 Update IMS docs
  src/pages/get-started/authentication/gs-authentication-token.md
Labels: technical
